config/routes.rb
Tongshare::Application.routes.draw do

  get "greeting/create"
  get "greeting/index"

  get "friendship/add_or_remove"
  get "friendship/show"

  get "profile/index"
  get "profile/show"
  get "profile/select"

  get "search/index"
  get "search/add_members"
  post "search/add_members"
  get "search/box"
  post "search/box"
  match "search/user/:keyword" => "search#user"
  match "search/location/:keyword" => "search#location"
  match "search/public_user/:keyword" => "search#public_user"
  match "search/public_group/:keyword" => "search#public_group"

  get "public/get_diff"
  match "public/user/:user_id" => "public#show_public_user"
  match "public/group/:group_id" => "public#show_public_group"
  match "public/location/:location" => "public#show_location"

  get "curriculum/upload"
  get "curriculum/save"
  post "curriculum/save"

  get "acceptance/create"
  get "acceptance/destroy"
  get "acceptance/deny"
  get "acceptance/accept"
  get "acceptance/exit"

  post "auth/confirm"

  get "thuauth/auth_with_xls_and_get_name"
  post "thuauth/auth_with_xls_and_get_name"

  devise_for :users, :controllers => {
    :registrations => "registrations_extended", 
    :sessions => "sessions_extended",
    :confirmations => "confirmations_extended"
    }

  get "home/index"

  get "sharings/add_members"
  post "sharings/add_members"

  get "groups/add_members"
  post "groups/add_members"
  get "groups/add_members"
  post "groups/set_members"

  resources :groups
  resources :events
  resources :sharings
  resources :acceptances

  root :to => "home#index"

end

app/controllers/registrations_extended_controller.rb
class RegistrationsExtendedController < Devise::RegistrationsController
include RegistrationsExtendedHelper
include UsersHelper
include AuthHelper

  def new
    super
    authorize! :create, resource
  end

  def create
    
    #if a user has already registered the employee_id but not confirmed, we will destroy the old one
    oldone = UserIdentifier.find_by(UserIdentifier::TYPE_EMPLOYEE_NO, params[:employee_no])
    oldone.user.destroy unless oldone.nil? || oldone.confirmed


    build_resource

    #add user identifiers
    resource.user_identifier.build \
      :login_type => UserIdentifier::TYPE_EMPLOYEE_NO,
      :login_value => company_domain + "." + params[:employee_no]

    if !params[:user][:email].nil? && !params[:user][:email].empty?
      resource.user_identifier.build \
        :login_type => UserIdentifier::TYPE_EMAIL,
        :login_value => params[:user][:email]
    end

    if !params[:mobile].nil? && !params[:mobile].empty?
      resource.user_identifier.build \
        :login_type => UserIdentifier::TYPE_MOBILE,
        :login_value => params[:mobile]
    end

    #go around for email validation:
    #devise will validate email's presence and uniqueness, however we allow users register with empty email
    #to pass the validation of devise, we create a random email with pattern sth@null.tongshare.com to represent empty email
    #duplicate: theoretically it is almost impossible.
    if params[:user][:email].nil? || params[:user][:email].empty?
      username = UUIDTools::UUID.random_create
      params[:user][:email] = "#{username}@null.#{company_domain(resource)}"
      resource.email = params[:user][:email]
    end

    authorize! :create, resource

    #skip email verify always
    resource.skip_confirmation!
    
    #do what devise does
    if resource.save
      set_flash_message :notice, :signed_up

      transfer_dummy_user(params[:employee_no], company_domain, resource.id)

      #backup the current redirect_to (according to stored_location_for)
      original_redirect = session[:user_return_to] || root_url
      puts "TEST REDIRECT: " + original_redirect
      unless (original_redirect.start_with?('/') || original_redirect.start_with?('http'))
        original_redirect = '/'+original_redirect
      end
      original_redirect = "http://" + SITE + original_redirect unless (original_redirect.include? SITE)
      #original_redirect = root_url

      #devise will do the redirect to session[:user_return_to]
      if !params[:infopass].blank?
        if (params[:infopass] == THU_SPECIAL_SECRET && params[:employee_no].start_with?('9999'))
          session[:user_return_to] = original_redirect
          ui = UserIdentifier.find_by UserIdentifier::TYPE_EMPLOYEE_NO, params[:employee_no]
          ui.confirmed = true
          user = ui.user
          user.build_user_extra if user.user_extra.nil?
          user.user_extra.public = true
          user.save!
          ui.save!
        else
          session[:user_return_to] = auth_path_with_password(params[:employee_no],
            params[:infopass], original_redirect)
        end
      else
        session[:user_return_to] = auth_path(params[:employee_no], original_redirect)
      end

      sign_in_and_redirect(resource_name, resource)
      #redirect_to auth_path_with_password(params[:employee_no], params[:infopass], original_redirect)
    else
      clean_up_passwords(resource)
      render_with_scope :new
    end

  end

  def edit
    resource.build_user_extra if current_user.user_extra.nil?
    authorize! :edit, resource

    if current_user
      if current_user.user_extra
        @photo_url = current_user.user_extra.photo_url
      end
    end
    super
  end

  def update
    authorize! :update, current_user

    if (params[:user][:email].nil? || params[:user][:email].empty?)
      username = UUIDTools::UUID.random_create
      params[:user][:email] = "#{username}@null.#{company_domain(resource)}"
      email_id = UserIdentifier.find_by_user_id_and_login_type(current_user.id, UserIdentifier::TYPE_EMAIL)
      email_id.destroy unless email_id.nil?
    end

    # TODO HACK THIS EMAIL FOR EXISTED DUMMY
    email = params[:user][:email]
    email_id = UserIdentifier.find_by(UserIdentifier::TYPE_EMAIL, email)
    if (email && !nil_email_alias?(email) && (!resource.confirmed? || email_id.nil? || email_id.login_value != email))
      params[:user][:email] = encode_email(email)
    end

    s = super
    return s if (s.class != String) # Something is wrong, so we returned.
    
    email = decode_email(resource.email)
    email_id = UserIdentifier.find_by(UserIdentifier::TYPE_EMAIL, email)
    if (!nil_email_alias?(email) && (!resource.confirmed? || email_id.nil? || email_id.login_value != email))
      # A very long hack to avoid email conflict with dummy
      dummy = check_or_create_general_dummy_user(UserIdentifier::TYPE_EMAIL, UserIdentifier::TYPE_EMAIL_DUMMY, email)
      dummy.email = "#{UUIDTools::UUID.random_create}@dummy.com"
      dummy.save!
      resource.email = email
      resource.send_confirmation_instructions
      resource.email = encode_email(email)
      resource.save!
      dummy.email = email
      dummy.save!
      flash[:notice] = I18n.t 'devise.confirmations_extended.send_instructions'
    end

    if (resource.user_extra.renren_url)
      resource.user_extra.profile_status = User::PROFILE_CONFIRMED
      resource.user_extra.save!
    end

    if (params[:user][:user_extra_attributes][:avatar])
      resource.user_extra.photo_url = resource.user_extra.avatar.url(:thumb)
      resource.user_extra.save!
    end
  end

  def destroy
    authorize! :destroy, current_user
    super
  end
end

app/helpers/registrations_extended_helper.rb
module RegistrationsExtendedHelper
  
  include UsersHelper
  #check if a given email is null alias (xxx@null.yyy.zzz)
  def nil_email_alias?(email, user = nil)
    not email.match(/.+@null.#{company_domain(user)}/).nil?
  end

  def more_login_used?
    return false if params.nil?
    return true if \
      !params[:user].nil? \
        && !params[:user][:email].nil? \
        && !params[:user][:email].empty? \
        && !nil_email_alias?(params[:user][:email])
    
    return true if !params[:mobile].nil? && !params[:mobile].empty?
    return false
  end

  def login_invalid?(field)
    return false if (!defined? resource || resource.valid?)

    login_errors = resource.errors[:login_value]
    return false if login_errors.nil?

    #logger.debug login_errors[0]
    #logger.debug(I18n.t "activerecord.errors.models.user_identifier.attributes.login_value.#{field}_invalid")
    login_errors.include?(I18n.t "activerecord.errors.models.user_identifier.attributes.login_value.#{field}_invalid")
  end

  def label_for_login(field)
    div_tag = login_invalid?(field) ? "<div class=\"field_with_errors\" style=\"display:inline\">".html_safe : "<div style=\"display:inline\">"
    field_name = I18n.t "activerecord.attributes.user_identifier.#{field.to_s}"
    
    content = <<HTML
    #{div_tag}
      <label for="#{field}" class="title">#{field_name}</label>
    </div>
HTML
    content.html_safe
  end

  def text_field_for_login(field)
    div_tag = login_invalid?(field) ? "<div class=\"field_with_errors\" style=\"display:inline\">".html_safe : "<div style=\"display:inline\">"
    field_tag = text_field_tag field, params[field], :max_length => UserIdentifier::MAX_VALUE_LENGTH, :class => "textvalue"

    content = <<HTML
    #{div_tag}
      #{field_tag}
    </div>
HTML
    content.html_safe
  end

  #create a dummy user with only user_id and an employee_no in user_identifier. raise exceptions when error occurs.
  #(1) If no user exists with "employee_no", create a dummy and return the new dummy user.
  #(2) If a dummy exists with "employee_no", return the existing dummy user.
  #(3) If a real user exists with "employee_no", return the existing real user.
  def check_or_create_dummy_user(employee_no, company_domain)
    #dummy_identifier = UserIdentifier.find_by_login_type_and_login_value(UserIdentifier::TYPE_EMPLOYEE_NO_DUMMY,
    #                company_domain + "." + employee_no)
    dummy_identifier = UserIdentifier.find(:first, :conditions => [
            "(login_type = ? OR login_type = ?) AND login_value = ?",
            UserIdentifier::TYPE_EMPLOYEE_NO_DUMMY,
            UserIdentifier::TYPE_EMPLOYEE_NO,
            company_domain + "." + employee_no
        ])
    return dummy_identifier.user if !dummy_identifier.nil?

    user = User.new :email => "#{UUIDTools::UUID.random_create}@null.#{company_domain}",
                    :password => random_password
    user.user_identifier.build :login_type => UserIdentifier::TYPE_EMPLOYEE_NO_DUMMY,
                               :login_value => company_domain + "." + employee_no
    user.skip_confirmation!
    user.save!
    user
  end

  # Generate dummy user with general login type (employee_no or email or anything else)
  def check_or_create_general_dummy_user(login_type, dummy_type, login_value)
    #dummy_identifier = UserIdentifier.find_by_login_type_and_login_value(UserIdentifier::TYPE_EMPLOYEE_NO_DUMMY,
    #                company_domain + "." + employee_no)
    dummy_identifier = UserIdentifier.find(:first, :conditions => [
            "(login_type = ? OR login_type = ?) AND login_value = ?",
            login_type,
            dummy_type,
            login_value
        ])
    return dummy_identifier.user if !dummy_identifier.nil?

    user = User.new :email => "#{UUIDTools::UUID.random_create}@null.#{company_domain}",
                    :password => random_password
    user.user_identifier.build :login_type => dummy_type, :login_value => login_value
    user.save!

    # In order to skip confirmation email sent to real email address,
    # we must change email after its first save(which will send out a confirmation email)
    if (login_type == UserIdentifier::TYPE_EMAIL)
      user.email = login_value
      user.save!
    end
    
    user
  end

  #Substitute the dummy user (if exist) with a real user. Transfer all data related to the dummy user to the real one, and delete the dummy
  def transfer_dummy_user(employee_no, company_domain, new_user_id)
    #try to find the dummy
    dummy_identifier = UserIdentifier.find_by_login_type_and_login_value(UserIdentifier::TYPE_EMPLOYEE_NO_DUMMY,
                        company_domain + "." + employee_no)
    return if dummy_identifier.nil?
    dummy = dummy_identifier.user
    
    UserSharing.update_all("user_id = #{new_user_id}", "user_id = #{dummy.id}")
    Membership.update_all("user_id = #{new_user_id}", "user_id = #{dummy.id}")

    dummy.destroy
  end

  #Substitute the dummy user (if exist) with a real user. Transfer all data related to the dummy user to the real one, and delete the dummy
  def transfer_general_dummy_user(dummy_type, dummy_value, new_user_id)
    #try to find the dummy
    dummy_identifier = UserIdentifier.find_by_login_type_and_login_value(dummy_type,
                        dummy_value)
    return false if dummy_identifier.nil?
    dummy = dummy_identifier.user

    UserSharing.update_all("user_id = #{new_user_id}", "user_id = #{dummy.id}")
    Membership.update_all("user_id = #{new_user_id}", "user_id = #{dummy.id}")

    dummy.destroy
  end

  def random_password(size = 8)
    chars = (('a'..'z').to_a + ('0'..'9').to_a) - %w(i o 0 1 l 0)
    (1..size).collect{|a| chars[rand(chars.size)] }.join
  end

  def try_set_email(email)
    return false if (email.nil? || nil_email_alias?(email) || email.blank?)
    email = decode_email(email)
    transfer_general_dummy_user(UserIdentifier::TYPE_EMAIL_DUMMY, email, current_user.id)
    current_user.email = email
    current_user.skip_confirmation!
    current_user.save!
    email_id = UserIdentifier.find_by_user_id_and_login_type(current_user.id, UserIdentifier::TYPE_EMAIL)
    email_id.destroy unless email_id.nil?
    UserIdentifier.create!(:user_id => current_user.id,
      :login_type => UserIdentifier::TYPE_EMAIL,
      :login_value => current_user.email,
      :confirmed => true)
  end

  SUPER_UNCOMMON_PREFIX = "NOBODY_SHOULD_USE_THIS_STRING_AS_EMAIL_PREFIX."

  def encode_email(email)
    if (email.start_with?(SUPER_UNCOMMON_PREFIX))
      return email
    else
      return SUPER_UNCOMMON_PREFIX + email
    end
  end

  def decode_email(email)
    if (email.start_with?(SUPER_UNCOMMON_PREFIX))
      return email[SUPER_UNCOMMON_PREFIX.length...email.length]
    else
      return email
    end
  end

end

app/views/registrations_extended/edit.html.erb
<%= content_box "个人", "资料" do %>
  <%= devise_error_messages_translated! %>
  <div id="profile_header">
  <table><tr>
  <td>
    <%= image_tag( ((@photo_url.nil? || @photo_url.blank?) ? 'default.jpg' : @photo_url), :onError => "this.src='/images/default.jpg';" ) %>
  </td>
  <td class="detail">
    <strong><%= current_user.friendly_name %></strong><br>
  </td>
  </tr></table>
  </div>
  <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :method => :put, :multipart => true }) do |f| %>
    
    <div class="stressed">以星号(*)开头的信息,只有您的好友可见</div><br/>
    <div class="field">
      <% resource[:email] = '' if defined?(resource) && (nil_email_alias?(resource[:email]) || !resource.confirmed?) %>
      <%= f.label :email, '*电子邮箱', :class=>"title" %>
      <%= f.text_field :email, :class=>"textvalue" %>
      <%#= f.label :email, "电子邮箱", :class=>"title" %>
      <%#= f.text_field :email, :class=>"textvalue" %>
    </div>

    <%= f.fields_for :user_extra do |extra| %>
      <div class="field">
        <label class="title">&nbsp;</label>
        <%= extra.check_box :reject_warning_flag %>
        <%= extra.label :reject_warning_flag, "不发送活动报警邮件到我的邮箱"%>
      </div>

    <% if current_user.user_extra && current_user.user_extra.public %>
      <div class="field">
        <%= extra.label :name, "名称", :class => 'title'%>
        <%= extra.text_field :name %>
      </div>
    <% end %>

      <div class="field">
        <%= extra.label :department, "院系", :class => 'title'%>
        <%= extra.text_field :department %>
      </div>

      <div class="field">
        <%= extra.label :address, "*寝室或住宅地址", :class => 'title'%>
        <%= extra.text_field :address %>
      </div>

      <div class="field">
        <%= extra.label :phone, "*寝室或固定电话", :class => 'title'%>
        <%= extra.text_field :phone %>
      </div>

      <div class="field">
        <label class="title">上传新头像</label>
        <%= extra.file_field :avatar %>
      </div>

      <div class="field">
        <%= extra.label :renren_url, "人人网个人主页", :class=>"title"%>
        <%= extra.text_field :renren_url, :class=>"textvalue" %>
        <div class="field_help">
          <div>想认识上同一节课的Ta吗？填写你的人人个人主页地址，让Ta找到你吧！</div>
          <div class="stressed">怎样获得人人网个人主页地址？</div>
          <div>
            <ul class="instruction_list">
              <li>登录<a href="http://www.renren.com" target="_blank">人人网</a></li>
              <li>登录后，点击页面上方的“个人主页”链接，从浏览器的地址栏中复制“个人主页”页面的地址。</li>
              <li>正确的地址类似于：http://www.renren.com/profile.do?id=356208904</li>
            </ul>
          </div>
        </div>
      </div>

      <div class="field">
        <label class="title">&nbsp;</label>
        <%= extra.check_box :hide_profile %>
        <%= extra.label :hide_profile, "不告诉一起参加活动的朋友们我的人人链接、头像以及院系"%>
      </div>
    <% end %>

    <div class="field">
      <label class="title">&nbsp;</label>
      <%= f.submit :submit, :value => "提交", :class => 'link1 commit_button' %>
      <%= styled_button "取消", :back %>
    </div>

  <% end %>
<% end %>

<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :method => :put }) do |f| %>
  <%= content_box "修改", "密码", true do %>

    <%= f.hidden_field :email, :class=>"textfield" %>
    <%= f.fields_for :user_extra do |extra| %>
      <div class="field">
        <%= extra.hidden_field :renren_url, :class=>"textfield" %>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :current_password, "原密码", :class=>"title" %>
      <%= f.password_field :current_password, :class=>"textvalue" %>
      <div class="field_help">
        需要您输入当前的“同享日程”密码以提高安全性。
      </div>
    </div>

    <div class="field">
      <%= f.label :password, "新密码", :class=>"title" %>
      <%= f.password_field :password, :class=>"textvalue" %>
        <div class="field_help">
          若不修改密码，请把这里留空
        </div>
    </div>

    <div class="field">
      <%= f.label :password_confirmation, "确认新密码", :class=>"title" %>
      <%= f.password_field :password_confirmation, :class=>"textvalue" %>
      <div class="field_help">
        若不修改密码，请把这里留空
      </div>
    </div>

    <div class="field">
      <label class="title">&nbsp;</label>
      <%= f.submit :submit, :value => "提交", :class => 'link1 commit_button' %>
      <%= styled_button "取消", :back %>
    </div>


    <br/>
    <div class="field" id="destroy_account">
        <span class="field_help"><%= link_to "将我的帐号永久删除", registration_path(resource_name), :confirm => "你确定要永久删号吗？你在“同享日程”上创建的所有活动及其它任何数据都将无法恢复！", :method => :delete %></span>
    </div>
  <% end %>

<% end  %>

app/views/registrations_extended/edit.mobile.erb
<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :method => :put }) do |f| %>
  <%= devise_error_messages_translated! %>

<p><strong>以星号(*)开头的信息（如电子邮件）将只有您的好友才能看到</strong></p>

  <p>
    <% resource[:email] = '' if defined?(resource) && (nil_email_alias?(resource[:email]) || !resource.confirmed?) %>
    <%= f.label :email, '*电子邮箱', :class=>"title" %>
    <%= f.text_field :email, :class=>"textvalue" %>
    <%#= f.label :email, "电子邮箱", :class=>"title" %>
    <%#= f.text_field :email, :class=>"textvalue" %>
  </p>

  <%= f.fields_for :user_extra do |extra| %>
    <p>
      <%= extra.check_box :reject_warning_flag %>
      <%= extra.label :reject_warning_flag, "不发送活动报警邮件到我的邮箱"%>
    </p>

    <p>
      <%= extra.label :department, "院系", :class => 'title'%>
      <%= extra.text_field :department %>
    </p>

    <p>
      <%= extra.label :address, "*寝室或住宅地址", :class => 'title'%>
      <%= extra.text_field :address %>
    </p>

    <p>
      <%= extra.label :phone, "*寝室或固定电话", :class => 'title'%>
      <%= extra.text_field :phone %>
    </p>

    <%= extra.label :renren_url, "人人网个人主页", :class=>"title"%>
    <%= extra.text_field :renren_url, :class=>"textvalue" %>
    <p>想认识上同一节课的Ta吗？填写你的人人个人主页地址，让Ta找到你吧！<br/>
      请访问<a href="http://3g.renren.com" target="_blank">手机人人</a>，登录后点击“个人主页”，并将其链接粘贴到这里。<br/>
      正确的地址类似于：<br/>
      http://3g.renren.com/profile.do?id=356208904&amp;(blablabla)<br/>
      或者：<br/>
      http://www.renren.com/profile.do?id=356208904<br/>
      如果用手机粘贴地址有困难，请使用电脑登录并粘贴你的人人地址。
    </p>
  <% end %>

  <%= f.submit "提交" %>
<% end %>

app/views/registrations_extended/new.html.erb
<%= content_box nil, "新用户注册" do %>
  <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
    <%= devise_error_messages_translated! %>
    <fieldset>
      <div class="field">
        <%= label_for_login :employee_no%>
        <%= text_field_for_login :employee_no%>
      </div>

      <div class="field"><%= f.label :password, '"同享日程"密码', :class=>"title" %>
        <%= f.password_field :password, :class=>"textvalue" %></div>

      <div class="field"><%= f.label :password_confirmation, '确认密码', :class=>"title"  %>
        <%= f.password_field :password_confirmation, :class=>"textvalue" %></div>

      <div class="field">
        <label class="title">&nbsp;&nbsp;</label>
        <div class="field_help">
          建议设置一个<span class="stressed">方便在手机上输入的密码</span>
        </div>
      </div>

      <div class="field">
        <label for="infopass" class="title">清华大学Info密码</label>
        <%= password_field_tag "infopass", nil, :class=>"textvalue"%>
      </div>

      <div class="field">
        <label class="title">&nbsp;&nbsp;</label>
        <span class="stressed">为什么要提供Info密码？</span>
        <div id="info_help">
          <div class="field_help">
            我们根据您的学号和Info密码来确认您的身份并自动获取您的姓名和课表。“同享日程”不会保存您的Info密码，也不会读取或保存除学号、姓名和课表以外的任何个人信息。
          </div>
        </div>
      </div>
      
      <%#*<div class="field">%>
        <%#*<label class="title">&nbsp;&nbsp;</label>%>
      <%#=
      link_to_function "更多登录方式（选填）", nil, :id => 'more_login_link' do |page|
        page.visual_effect :toggle_blind, 'more_login', :duration => 0.5
      end%>
    <%#*</div>%>


      <%#*<div id="more_login"%>
          <%#= more_login_used? ? "" : 'style="display:none"'.html_safe%>
           <%#*>%>
        <%# resource[:email] = '' if defined?(resource) && nil_email_alias?(resource[:email]) %>
        <%#*<div class="field">%>
          <%#= f.label :email, '电子邮件', :class=>"title" %>
          <%#= f.text_field :email, :class=>"textvalue" %>
    <%#*</div>%>

        <%#*<div class="field">%>
          <%#= label_for_login :mobile %>
          <%#= text_field_for_login :mobile %>
    <%#*</div>%>
      <%#*</div>%>

      <p><%= submit_button f, "user_new", "注册" %></p>
    </fieldset>
  <% end %>
<% end %>

app/views/registrations_extended/new.mobile.erb
<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>

<%= devise_error_messages_translated! %>

<%= label_for_login :employee_no%><br/>
<%= text_field_for_login :employee_no%><br/>

<%= f.label :password, '“同享日程”密码'%><br/>
<%= f.password_field :password, :size => nil%><br/>

<%= f.label :password_confirmation, '确认密码', :class=>"title"  %><br/>
<%= f.password_field :password_confirmation, :class=>"textvalue", :size => nil %><br/>

<label for="infopass">清华大学Info密码</label><br/>
<%= password_field_tag "infopass", nil%><br/>

<p>我们根据您的学号和Info密码来确认您的身份并自动获取您的姓名和课表。“同享日程”不会保存您的Info密码，也不会读取或保存除学号、姓名和课表以外的任何个人信息。
</p>

<%= f.submit "注册"%>

<% end %>