config/routes.rb
Tongshare::Application.routes.draw do

  get "greeting/create"
  get "greeting/index"

  get "friendship/add_or_remove"
  get "friendship/show"

  get "profile/index"
  get "profile/show"
  get "profile/select"

  get "search/index"
  get "search/add_members"
  post "search/add_members"
  get "search/box"
  post "search/box"
  match "search/user/:keyword" => "search#user"
  match "search/location/:keyword" => "search#location"
  match "search/public_user/:keyword" => "search#public_user"
  match "search/public_group/:keyword" => "search#public_group"

  get "public/get_diff"
  match "public/user/:user_id" => "public#show_public_user"
  match "public/group/:group_id" => "public#show_public_group"
  match "public/location/:location" => "public#show_location"

  get "curriculum/upload"
  get "curriculum/save"
  post "curriculum/save"

  get "acceptance/create"
  get "acceptance/destroy"
  get "acceptance/deny"
  get "acceptance/accept"
  get "acceptance/exit"

  post "auth/confirm"

  get "thuauth/auth_with_xls_and_get_name"
  post "thuauth/auth_with_xls_and_get_name"

  devise_for :users, :controllers => {
    :registrations => "registrations_extended", 
    :sessions => "sessions_extended",
    :confirmations => "confirmations_extended"
    }

  get "home/index"

  get "sharings/add_members"
  post "sharings/add_members"

  get "groups/add_members"
  post "groups/add_members"
  get "groups/add_members"
  post "groups/set_members"

  resources :groups
  resources :events
  resources :sharings
  resources :acceptances

  root :to => "home#index"

end

app/models/group.rb
class Group < ActiveRecord::Base
  # the length here is UTF8 char length
  MAX_NAME_LENGTH = 32
  MAX_EXTRA_INFO_LENGTH = 4096
  MAX_IDENTIFIER_LENGTH = 16

  # will there be more privacies?
  PRIVACY_PUBLIC = 0
  PRIVACY_PRIVATE = 1

  attr_accessible :name, :extra_info, :identifier, :creator_id, :privacy

  belongs_to :creator, :class_name => "User"
  has_many :membership, :dependent => :destroy
  has_many :group_sharing, :dependent => :destroy

  validates :name, :creator_id, :presence => true
  #validates :identifier, :uniqueness => true
  validates_length_of :name, :maximum => MAX_NAME_LENGTH
  validates_length_of :extra_info, :maximum => MAX_EXTRA_INFO_LENGTH
  #validates_length_of :identifier, :maximum => MAX_IDENTIFIER_LENGTH
  validate do |group|
      query = Group.where(:creator_id => group.creator_id, :name => group.name)
      errors.add :name, :already_exists if query.exists? and query.first.id != group.id
  end

  #return nil if the user is not a member of this group
  def member_power(user)
    return nil if user.nil?
    # TODO is this right?
    return Membership::POWER_SUPER_MANAGER if user.id == self.creator_id
    result = membership.find_by_user_id user.id
    return nil if result.nil?
    return result.power
  end

  def set_member_power(user, power)
    return false if user.nil?
    return false if user.id == self.creator_id
    result = membership.find_by_user_id user.id
    return false if result.nil?
    result.power = power
    result.save
  end

  def members
    self.membership.map{|ms| ms.user}
  end

  #TODO need test
  def has_member?(user)
    return (self.membership.find_by_user_id(user.id) != nil)
  end

  def add_member (login_type, login_value, power = Membership::POWER_MEMBER)
    user = UserIdentifier.find_user_by(login_type, login_value)
    return nil if user.nil?
    ms = user.membership.new(
      :group_id => self.id,
      :power => power
    )
    ms.save
  end

  def add_member (user, power = Membership::POWER_MEMBER)
    return nil if user.nil?
    ms = user.membership.new(
      :group_id => self.id,
      :power => power
    )
    ms.save
  end

  # members is an array constructed with hashes of {:user_id or (:login_type and :login_value) and :power}
  #
  def set_members (members)
    self.membership.delete_all
    self.membership(true) #TODO What does this mean?
    members.each do |member|
      user_id = member[:user_id] if User.where(:id => member[:user_id]).exists?
      if user_id.nil?
        user = UserIdentifier.find_user_by(member[:login_type], member[:login_value])
        user_id = user.id if !user.nil?
      end
      power = member[:power]
      next if user_id.nil? or power.nil? or user_id == self.creator_id
      self.membership.build(
        :user_id => user_id,
        :power => power
      )
    end
    self.save
  end

  # members is an array constructed with hashes of {:user_id or (:login_type and :login_value)}
  #
  def set_managers(managers)
    self.membership.where(:power => Membership::POWER_MANAGER).delete_all
    managers.each do |manager|
      user_id = manager[:user_id] if (manager[:user_id] && User.where(:id => manager[:user_id]).exists?)
      if (user_id.nil?)
        user = UserIdentifier.find_user_by(manager[:login_type], manager[:login_value])
        user_id = user.id if !user.nil?        
      end
      next if user_id.nil?
      membership = self.membership.find_by_user_id(user_id)
      if (membership)
        membership.power = Membership::POWER_MANAGER
        membership.save!
      else
        self.membership.build(:user_id => user_id, :power => Membership::POWER_MANAGER)
      end
    end
    self.save!
  end

  # Note that managers do not include creator!
  def managers()
    self.membership.where(:power => Membership::POWER_MANAGER).map{ |x| x.user }
  end

  def remove_member (user)
    return nil if user.nil?
    ms = membership.find :first, :user => user
    return nil if ms.nil?
    ms.destroy
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  include SharingsHelper
  include RegistrationsExtendedHelper
  include UsersHelper
  include EventsHelper
  include GroupsHelper

  before_filter :authenticate_user!

  def add_members
    result = {:valid => [], :dummy => [], :new_email => [], :duplicated => [], :invalid => [], :parse_errored => []}

    items = parse_sharings_raw(params[:raw_string])

    if (params[:friend_id] && !params[:friend_id].blank?)
      begin
        friend = User.find(params[:friend_id].to_i)
        uid = friend.user_identifier.first
        items << {:type => :uid, :uid => uid}
      rescue ActiveRecord::RecordNotFound
      end
    end

    if (params[:group_id] && !params[:group_id].blank?)
      begin
        group = Group.find(params[:group_id].to_i)
        if (group.privacy == Group::PRIVACY_PRIVATE) # Only private groups can be invited(public group recommendation is not supported yet)
          for membership in group.membership
            user = membership.user
            uid = user.user_identifier.first
            if (uid.login_type == UserIdentifier::TYPE_EMPLOYEE_NO_DUMMY)
              items << {:type => UserIdentifier::TYPE_EMPLOYEE_NO, :login_value => uid.login_value.match(/\d+$/)[0]}
            elsif (uid.login_type == UserIdentifier::TYPE_EMAIL_DUMMY)
              items << {:type => UserIdentifier::TYPE_EMAIL, :login_value => uid.login_value}
            else
              items << {:type => :uid, :uid => uid}
            end
          end
        elsif (group.privacy == Group::PRIVACY_PUBLIC) # only show managers for public group
          for membership in group.membership
            next if membership.power != Membership::POWER_MANAGER
            user = membership.user
            uid = user.user_identifier.first
            if (uid.login_type == UserIdentifier::TYPE_EMPLOYEE_NO_DUMMY)
              items << {:type => UserIdentifier::TYPE_EMPLOYEE_NO, :login_value => uid.login_value.match(/\d+$/)[0]}
            elsif (uid.login_type == UserIdentifier::TYPE_EMAIL_DUMMY)
              items << {:type => UserIdentifier::TYPE_EMAIL, :login_value => uid.login_value}
            else
              items << {:type => :uid, :uid => uid}
            end
          end
        end
      rescue ActiveRecord::RecordNotFound
      end
    end

    for item in items
      if item[:type].nil?
        result[:parse_errored] << item[:login_value]
        next
      end

      ui = item[:type] == :uid ? item[:uid] : UserIdentifier.find_by(item[:type], item[:login_value])
      if !ui.nil?
        begin
          name = (ui.user.user_extra.name) + (item[:login_value] ? "(#{item[:login_value]})" : "")
        rescue Exception
          name = item[:login_value]
        end
        data_entry = {:id => ui.user_id, :name => name, :conflict => []}  #do not expose user_friendly_name or attackers can enumerate 学号/姓名 pair by add sharings.

        result[:valid] << data_entry
      elsif item[:type] == UserIdentifier::TYPE_EMPLOYEE_NO
        result[:dummy] << item[:login_value]
      elsif item[:type] == UserIdentifier::TYPE_EMAIL
        result[:new_email] << item[:login_value]
      else
        result[:invalid] << item[:login_value]
      end
    end

    @json = result.to_json

    respond_to do |format|
      format.js
    end
  end

  def set_members
    members = []
    #prepare dummy users
    if !params[:dummy].nil?
      params[:dummy].each do |employee_no|
        dummy = check_or_create_dummy_user(employee_no, company_domain)
        #if an illegal employee_no is submitted in params[:dummy], check_or_create_dummy_user will raise exceptions since it calls User.save! and the value won't pass validation.
        members << dummy.id
      end
    end
    if !params[:new_email].nil?
      params[:new_email].each do |new_email|
        dummy = check_or_create_general_dummy_user(UserIdentifier::TYPE_EMAIL, UserIdentifier::TYPE_EMAIL_DUMMY, new_email)
        #if an illegal employee_no is submitted in params[:dummy], check_or_create_dummy_user will raise exceptions since it calls User.save! and the value won't pass validation.
        members << dummy.id
      end
    end

    #add normal users
    if !params[:members].nil?
      params[:members].each do |id|
        members << id.to_i
      end
    end

    if (params[:group_name] && !params[:group_name].blank?)
      if (current_user.public?)
        group = query_or_create_public_group(params[:group_name], current_user)
      else
        group = query_or_create_group_via_name_and_creator_id(params[:group_name], current_user.id)
      end
      authorize! :edit, group
      group_members = members.map do |member_id|
        {:user_id => member_id, :power => Membership::POWER_MEMBER}
      end

      if (current_user.public?)
        group.set_managers(group_members)
      else
        group.set_members(group_members)
      end
      group.save!
      flash[:notice] = '操作成功'
    else
      flash[:alert] = '群组名不能位空'
    end
    redirect_to '/groups/'
  end

  def index
  end

  # GET /groups/1
  # GET /groups/1.xml
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.xml
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.xml
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to(@group, :notice => 'Group was successfully created.') }
        format.xml  { render :xml => @group, :status => :created, :location => @group }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.xml
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to(@group, :notice => 'Group was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.xml
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to(groups_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def add_group(name, creator_id = current_user_id, privacy = Group::PRIVACY_PRIVATE, extra_info = nil)
    group = Group.new(:creator_id => creator_id, :name => name, :privacy => privacy, :extra_info => extra_info)
    group.save
  end

  def query_group_via_name_and_creator_id(name, creator_id)
    Group.where(:name => name, :creator_id => creator_id).first
  end

  def query_or_create_group_via_name_and_creator_id(name, creator_id)
    g = Group.where(:name => name, :creator_id => creator_id).first
    if g.nil?
      add_group(name, creator_id)
      g = Group.where(:name => name, :creator_id => creator_id).first
    end
    return g
  end

  def query_or_create_public_group(name, creator)
    return nil if (!creator.user_extra | !creator.user_extra.public) # only public user can create public group
    g = Group.where(:name => name, :privacy => Group::PRIVACY_PUBLIC).first
    return g if g # Note that name might conflict!
    add_group(name, creator.id, Group::PRIVACY_PUBLIC)
    g = Group.where(:name => name, :privacy => Group::PRIVACY_PUBLIC).first
    return g
  end

end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :extra_info %><br />
    <%= f.text_area :extra_info %>
  </div>
  <div class="field">
    <%= f.label :identifier %><br />
    <%= f.text_field :identifier %>
  </div>
  <div class="field">
    <%= f.label :creator_id %><br />
    <%= f.text_field :creator_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<% content_for :js_ext do %>
  <%= javascript_include_tag "group.js" %>
  <%= javascript_include_tag "dhtmlx/dhtmlxcommon.js" %>
  <%= javascript_include_tag "dhtmlx/dhtmlxcombo.js" %>
  <%= javascript_include_tag "pinyin.js" %>
<% end %>

<link rel="STYLESHEET" type="text/css" href="../stylesheets/dhtmlx/dhtmlxcombo.css"/>
<script>
  window.dhx_globalImgPath="../images/dhtmlx/";
</script>

<%= content_box "管理", (current_user.public? ? "公共群组" : "我的群组"), true do %>
  <%= form_tag url_for(:action => "add_members"), :remote => true, :onsubmit => 'confirmComboValue();' do %>
      <fieldset>
        <div class="field">
          <label for="group_id" class="title"><%= (current_user.public? ? "公共群组" : "我的群组")%></label>
          <select style='width:200px;'  id="groups_combo" name="group_id" onChange="clear();checkNewGroup();raw_string_onblur();">
            <option value="new">新建群组</option>
            <% for group in current_user.group %>
              <option value="<%= group.id %>"><%= group.name %></option>
            <% end %>
          </select>
          <script>
            var groups_combo=dhtmlXComboFromSelect("groups_combo");
            groups_combo.enableFilteringMode(true);
            groups_combo.setComboText('')
            groups_combo.unSelectOption()
            groups_combo.attachEvent("onOpen", function(){groups_combo.setComboText('')})
          </script>
        </div>
        <div class="field">
          <label for="friend_id" class="title">添加我的好友</label>
          <select style='width:200px;'  id="friends_combo" name="friend_id" onChange="raw_string_onblur();">
            <% for f_to in current_user.friendship_to.where('property=?', Friendship::BIDIRECTIONAL) %>
              <option value="<%= f_to.to_user_id %>"><%= f_to.to_user.friendly_name %></option>
            <% end %>
          </select>
          <script>
            var friends_combo=dhtmlXComboFromSelect("friends_combo");
            friends_combo.enableFilteringMode(true);
            friends_combo.setComboText('')
            friends_combo.unSelectOption()
            friends_combo.attachEvent("onOpen", function(){friends_combo.setComboText('')})
          </script>
          <div class="field_help">您可以用Ta的名字拼音首字母来快速定位到Ta</div>
        </div>
        <div class="field">
          <label for="raw_string" class="title">添加普通用户</label>
          <%= text_area_tag "raw_string", nil, :class=>"textfield_narrow", :onkeyup=>"raw_string_onkeyup(typeof(e)=='undefined'?event:(e || event));", :onblur=>"raw_string_onblur();"%>
        </div>
        <div class="field">
          <label class="title">&nbsp;</label>
          <div class="field_help">粘贴或填写要查询的用户的学号或电子邮件地址，有多个时可以使用逗号、分号、空格、制表符或换行符分隔。</div>
        </div>
        <div class="field">
          <label class="title">&nbsp;</label>
    <%#= submit_button nil, "add_members_form", "添加"%>
          <%= submit_tag "添加", :id => "add_members_submit" %>
        </div>
      </fieldset>
    <% end %>

  <%= form_tag url_for(:action => "set_members") do %>
    <fieldset>
      <div class="field">
        <div id="group_name_container" class="field" style="display:none">
          <label for="group_name" class="title">群组名</label>
          <%= text_field_tag "group_name"%>
        </div>
        <label class="title"><%= (current_user.public? ? "群组管理员" : "群组成员") %> </label>
        <div id="new_member_nil" class="field_div">（请在上面的文本框中添加邀请对象，完成后单击“添加”按钮）</div>
        <div id="new_members_container" class="field_div">
          <ul id="new_members">
          </ul>
          <br/>
        </div>
        <div id="new_dummy_container" class="field_div" style="display:none">
          <ul id="new_dummy"></ul>
           <br/>
        </div>
        <div id="new_email_container" class="field_div" style="display:none">
          <ul id="new_email"></ul>
           <br/>
        </div>

        <div id="errors_container">
          <div id="errors_invalid_container" class="field_div" style="display:none">
            以下用户没有注册且无法获取其学号或电子邮件，因此无法收到活动分享：
            <ul id="errors_invalid"></ul>
             <br/>
          </div>
          <div id="errors_parse_errored_container" class="field_div" style="display:none">
            无法解析以下字串：
            <ul id="errors_parse_errored"></ul>
             <br/>
          </div>
        </div>
      </div>

        <div class="field">
          <label class="title">&nbsp;</label>
          <%= submit_tag( (current_user.public? ? "设置群组管理员" : "设置群组成员"), :id => "set_members_submit" )%>
        </div>
      <% end %>
    </fieldset>
<% end %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @group.name %>
</p>

<p>
  <b>Extra info:</b>
  <%= @group.extra_info %>
</p>

<p>
  <b>Identifier:</b>
  <%= @group.identifier %>
</p>

<p>
  <b>Creator:</b>
  <%= @group.creator_id %>
</p>


<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>