config/routes.rb
Tongshare::Application.routes.draw do

  get "greeting/create"
  get "greeting/index"

  get "friendship/add_or_remove"
  get "friendship/show"

  get "profile/index"
  get "profile/show"
  get "profile/select"

  get "search/index"
  get "search/add_members"
  post "search/add_members"
  get "search/box"
  post "search/box"
  match "search/user/:keyword" => "search#user"
  match "search/location/:keyword" => "search#location"
  match "search/public_user/:keyword" => "search#public_user"
  match "search/public_group/:keyword" => "search#public_group"

  get "public/get_diff"
  match "public/user/:user_id" => "public#show_public_user"
  match "public/group/:group_id" => "public#show_public_group"
  match "public/location/:location" => "public#show_location"

  get "curriculum/upload"
  get "curriculum/save"
  post "curriculum/save"

  get "acceptance/create"
  get "acceptance/destroy"
  get "acceptance/deny"
  get "acceptance/accept"
  get "acceptance/exit"

  post "auth/confirm"

  get "thuauth/auth_with_xls_and_get_name"
  post "thuauth/auth_with_xls_and_get_name"

  devise_for :users, :controllers => {
    :registrations => "registrations_extended", 
    :sessions => "sessions_extended",
    :confirmations => "confirmations_extended"
    }

  get "home/index"

  get "sharings/add_members"
  post "sharings/add_members"

  get "groups/add_members"
  post "groups/add_members"
  get "groups/add_members"
  post "groups/set_members"

  resources :groups
  resources :events
  resources :sharings
  resources :acceptances

  root :to => "home#index"

end

app/views/shared/_agenda.html.erb
<div class="agenda_list" id="my_events">
  <%= content_box @name, "的日程", false do %>

<%
  week_str = number_of_week_in_thu
  week_str = "，#{week_str}" unless week_str.blank?
%>
<div id="current_time">现在是<%= l Time.now, :format => :long %><%=week_str%>。</div>

    <div class="agenda_pannel">
      <ul>
        <li><%= link_to_unless (@range == :next && @offset == 0), "接下来", {:range => :next} %></li>
        | <li><%= link_to_unless_current "按天", {:range => :day, :offset => 0} %></li>
        | <li> <%= link_to_unless_current "按周", {:range => :week, :offset => 0} %></li>
      </ul>
    </div>
    <% if @instances.length > 0 %>
    <div id="agenda_list_content">
    <% @instances.each do |instance|%>
      <%= div_for(instance, :class => "item") do %>
        <% if !@only_public || instance.event.public? %>
          <div class="instance name">
            <%= link_to instance.name, event_path(instance.event, :inst => instance.id), :title => instance.extra_info%>
            <%= "（有报警！）" if instance.warning_count > 0%>
          </div>
          <div class="instance info">
            <span><%=instance.location%></span>
            <span>
              <%= friendly_time_range instance.begin, instance.end %>
            </span>
          </div>
          <div class="instance links">
            <%#*<span>%>
              <%#= link_to "分享", :controller => "sharings", :action => "new", :event_id => instance.event.id %>
            <%#*</span>%>


            <span>
              <% event = instance.event %>
              <%= link_to "编辑", edit_event_path(instance.event) if can? :edit, event %>
              <%= link_to "删除", event, :method => "delete",
                    :confirm => ("你确实要删除\"#{instance.name}\"吗？" + (event.recurring? ? "这是一个重复的事件，所有重复项都会被删除！" : "")) \
                    if can? :destroy, event
              %>
            </span>
          </div>
        <% else %>
          <div class="instance name">
            非公开的活动
          </div>
          <div class="instance info">
            <span>
              <%= friendly_time_range instance.begin, instance.end %>
            </span>
          </div>
        <% end %>
      <% end %>
    <% end %>
    </div>
    <% else %>
    <p style="padding-left: 20px; color: #f85811">没有活动了</p>
    <% end %>
    <% if @range == :next %>
      <div>
        <% if @offset == 0 %>
          <% if @limit != 0 %>
            以上是即将发生的前<%=@limit%>个活动
          <% end %>
        <% else %>
          以上是即将发生的第<%=@offset + 1%>个到<%=@offset + @limit%>个活动。
        <% end %>
        <%= link_to "之前的活动", {:offset => [0, @offset - 10].max} if @offset > 0 %>
        <%= link_to "之后的活动", {:offset => @offset + 10} if !@is_last_page %>
      </div>
    <% end %>
    <% unit = params[:range] == "day" ? '天' : params[:range] == "week" ? '周' : nil %>
    <% if unit %>
    <div class="agenda_pannel">
      <ul>
        <li><%= link_to "前一"+unit, {:range => params[:range], :offset => params[:offset].to_i-1} %></li>
        | <li> <%= link_to "下一"+unit, {:range => params[:range], :offset => params[:offset].to_i+1} %></li>
      </ul>
    </div>
    <% end %>

  <%end%>
</div>

app/views/shared/_agenda.html.erb.erb
<div class="agenda_list" id="my_events">
  <%= content_box @name, "的日程", false do %>

<%
  week_str = number_of_week_in_thu
  week_str = "，#{week_str}" unless week_str.blank?
%>
<div id="current_time">现在是<%= l Time.now, :format => :long %><%=week_str%>。</div>

    <div class="agenda_pannel">
      <ul>
        <li><%= link_to_unless (@range == :next && @offset == 0), "接下来", {:range => :next} %></li>
        | <li><%= link_to_unless_current "按天", {:range => :day, :offset => 0} %></li>
        | <li> <%= link_to_unless_current "按周", {:range => :week, :offset => 0} %></li>
      </ul>
    </div>
    <% if @instances.length > 0 %>
    <div id="agenda_list_content">
    <% @instances.each do |instance|%>
      <%= div_for(instance, :class => "item") do %>
        <div class="instance name">
          <%= link_to instance.name, event_path(instance.event, :inst => instance.id), :title => instance.extra_info%>
          <%= "（有报警！）" if instance.warning_count > 0%>
        </div>
        <div class="instance info">
          <span><%=instance.location%></span>
          <span>
            <%= friendly_time_range instance.begin, instance.end %>
          </span>
        </div>
        <div class="instance links">
          <%#*<span>%>
            <%#= link_to "分享", :controller => "sharings", :action => "new", :event_id => instance.event.id %>
          <%#*</span>%>


          <span>
            <% event = instance.event %>
            <%= link_to "编辑", edit_event_path(instance.event) if can? :edit, event %>
            <%= link_to "删除", event, :method => "delete",
                  :confirm => ("你确实要删除\"#{instance.name}\"吗？" + (event.recurring? ? "这是一个重复的事件，所有重复项都会被删除！" : "")) \
                  if can? :destroy, event
            %>
          </span>
        </div>
      <% end %>
    <% end %>
    </div>
    <% else %>
    <p style="padding-left: 20px; color: #f85811">没有活动了</p>
    <% end %>
    <% if @range == :next %>
      <div>
        <% if @offset == 0 %>
          <% if @limit != 0 %>
            以上是即将发生的前<%=@limit%>个活动
          <% end %>
        <% else %>
          以上是即将发生的第<%=@offset + 1%>个到<%=@offset + @limit%>个活动。
        <% end %>
        <%= link_to "之前的活动", {:offset => [0, @offset - 10].max} if @offset > 0 %>
        <%= link_to "之后的活动", {:offset => @offset + 10} if !@is_last_page %>
      </div>
    <% end %>
    <% unit = params[:range] == "day" ? '天' : params[:range] == "week" ? '周' : nil %>
    <% if unit %>
    <div class="agenda_pannel">
      <ul>
        <li><%= link_to "前一"+unit, {:range => params[:range], :offset => params[:offset].to_i-1} %></li>
        | <li> <%= link_to "下一"+unit, {:range => params[:range], :offset => params[:offset].to_i+1} %></li>
      </ul>
    </div>
    <% end %>

  <%end%>
</div>

app/views/shared/_agenda.mobile.erb
<h2><%= @name %>的日程</h2>

<%= l Time.now, :format => :long %> <%=  number_of_week_in_thu %> <br/>

<%= link_to_unless_current "接下来", {:range => :next} %>&nbsp;&nbsp;
<%= link_to_unless_current "今天", {:range => :day, :offset => 0} %>&nbsp;&nbsp;
<%= link_to_unless_current "明天", {:range => :day, :offset => 1} %>&nbsp;&nbsp;
<%= link_to_unless_current "本周", {:range => :week, :offset => 0} %>&nbsp;&nbsp;
<%= link_to_unless_current "下周", {:range => :week, :offset => 1} %>&nbsp;&nbsp;
<br/><br/>

<% @instances.each do |instance|%>
  <% if !@only_public || instance.event.public? %>
    <%= link_to instance.name, event_path(instance.event, :inst=>instance.id) %>
    <% if instance.warning_count > 0 %>
    <font color="red">（有报警！）</font>
    <% end %>
    <br/>
    <%= instance.location.blank? ? "" : (instance.location + "<br/>").html_safe%>
    <%= friendly_time_range instance.begin, instance.end %>
    <%#= link_to "删除", instance.event, :method => "delete" %>
    <br/>
  <% else %>
    非公开的活动<br/>
    <%= friendly_time_range instance.begin, instance.end %>
  <% end %>
  <% event = instance.event %>
  <hr/>
<% end %>

<% if @range == :next %>
    <% if @offset == 0 %>
      以上是即将发生的前<%=@limit%>个活动
    <% else %>
      以上是即将发生的第<%=@offset + 1%>个到<%=@offset + @limit + 1%>个活动。
    <% end %><br/>
    <%= link_to "之前的活动", {:offset => [0, @offset - 10].max} if @offset > 0 %>
    <%= link_to "之后的活动", {:offset => @offset + 10} if !@is_last_page %>
<% end %>

app/views/shared/_header_announcement.html.erb
<div id="header_ann">
  <ul>
    <% if @num_friendship_from - @num_friendship_bidirectional > 0 %>
    <li>
      <%= link_to "有" + (@num_friendship_from-@num_friendship_bidirectional).to_s + "个人想加你为好友。", url_for(:controller => :friendship, :action => :show, :type => :only_from) %>
    </li>
    <% end %>

    <% if @invited_user_sharings && @invited_user_sharings.count > 0 %>
    <li><%= link_to sprintf("有%d个邀请正等待你的回复", @invited_user_sharings.count), '#invited_events' %></li>
    <% end %>

    <% if @not_confirmed %>
      <li>
        <span class="stressed">未通过身份验证！</span>
          请立即
          <%= link_to "重新验证", @auth_path%>。<a href="#" title="如果未通过身份验证，系统将无法导入你的课表，且其它用户可以在注册时覆盖你的学号，从而导致你的账户丢失！（由于系统升级，原先一些被错误通过验证的用户现在可能需要重新验证）">( ? )</a>
      </li>
    <% end %>

    <% if @curriculum_empty %>
      <li>
        <span class="stressed">课表有问题？</span>
        尝试<%= link_to "通过课表文件导入课表", {:controller=>"curriculum", :action=>"upload"}%>
      </li>
    <% end %>
    <% if !current_user.has_valid_email %>
      <li>
        <span class="stressed">还没有填写邮箱或通过邮箱验证？</span>
        请<%= link_to "填写邮箱地址", edit_user_registration_path %>, 并去邮箱接收验证邮件
      </li>
    <% end %>

    <% if @renren_url_empty %>
      <li>
        <span class="stressed">让Ta找到你！</span>
        立即<%= link_to "填写人人网个人主页地址", edit_user_registration_path%>
      </li>
    <% end %>
  </ul>
</div>

app/views/shared/_header_announcement.mobile.erb
<% if @not_confirmed %>
<p><strong>注意！</strong>
    系统未能验证你的学号，请立即
    <strong><%= link_to "重新验证", @auth_path%></strong><br/>
    如果学号未通过验证，系统将无法导入你的课表，并且其它用户可以在注册时<strong>覆盖该学号，从而导致你的
    同享日程账户丢失！</strong>（由于系统升级，原先一些被错误通过验证的用户现在可能需要重新验证）
</p>
<% end %>

<% if @curriculum_empty %>
<p><strong>课表有问题？</strong>
  请尝试用电脑登录并通过Excel课表文件导入课表
</p>
<% end %>

<% if @renren_url_empty && false %>
<p>
  <strong>让Ta找到你！</strong>
   立即<%= link_to "填写人人网个人主页地址", edit_user_registration_path%>
</p>
<% end %>

<p>
<% if @note.is_a? Array %>
<%= link_to @note[0], @note[1] %>
<%else%>
<%= @note %>
<%end%>
</p>

app/views/shared/_note.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<% if @note.is_a? Array %>
<%= link_to @note[0], 'http://' + SITE + @note[1] %>
<%else%>
<%= @note %>
<%end%>

app/views/shared/_sidebar_announcement.html.erb
<div id="sidebar_ann" class="inside">
  <div class="subtitle">最近更新：</div>
  <ul>
    <li>
      <b>分享活动</b> 把你的活动分享给好朋友一起参加，寻找大家共同空余的时间并且即时掌握大家参加意愿的反馈～
    </li>
    <li><b>添加好友</b> 你可以把你认识的那些和你参加同一个活动的同学添加为好友，方便以后一起利用tongshare同享日程，组织活动～</li>
    <li><b>打招呼</b> 给你你想认识的同学打个招呼吧~</li>
    <li><b>丰富个人信息</b> <%= link_to '填写更丰富的个人信息', edit_user_registration_path %>，方便好友联系认识你～</li>
    <li><b>上传头像</b> 同享日程将自动链接您的人人头像，您也可以自己<%= link_to '上传新的头像', '/users/edit' %></li>
    <li><b>看谁有空</b> 想创建活动找朋友一起来参加，但是不知道Ta什么时间有空？<%= link_to '快去查询一下吧～', :controller => "search"%> </li>
    
    <li>
      <b>邮件提醒</b> 又点名了？不用怕，一有情况立即自动邮件提醒！还不赶快去<%= link_to '填写邮箱', edit_user_registration_path%> ～
    </li>
  <li>
    <b>手动上传课表</b> 课表依然导入失败？只好<%= link_to "手动上传课表文件", {:controller => "curriculum", :action => "upload"}%>
    </li>
  </ul>
</div>

app/views/shared/_user_profile.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<tr><td>
  <table class="user_profile"><tr>
  <td><%= image_tag( ((@photo_url.nil? || @photo_url.blank?) ? 'default.jpg' : @photo_url), :onError => "this.src='/images/default.jpg';" ) %></td>
  <td>
    <dl>
      <dt>
        <% if @user.public? %>
          <%= link_to @name, '/public/user/'+@user.id.to_s, :class => "title_name" %>
        <% else %>
          <%=@name%>
          <% unless (@renren_url.nil? || @renren_url.blank?) %>
            <%= link_to @renren_url, :target=>"_blank", :title=>"访问#{@name}的人人网个人主页" do %>
              <%= image_tag 'renren.png'%>
            <% end %>
            <% if @unconfirmed %>
              <% notice = '人人链接旁边的（？）表示同享日程显示的人人链接并没有得到其本人的确认，但是同享日程觉得这很有可能就是其本人的人人链接' %>
              <%= link_to '（?）', request.request_uri + (request.request_uri.include?('?') ? '&' : '?') + 'notice=' + notice, :title => notice %>
            <% end %>
          <% else %>
            &nbsp;
          <% end %>
        <% end %>
      </dt>
      <% if @department && !@department.blank? %>
      <dl><%= @department %></dl>
      <% end %>
    <% if @can_be_selected %>
      <dl>
      <%=  link_to "这是我的人人链接", url_for(:controller => :profile, :action => :select, :renren_url => @renren_url, :department => @department, :photo_url => @photo_url) %>
      </dl>
    <% elsif (current_user && @user.id != current_user.id) %>
      <% if @event %>
      <dl>
        <%= link_to '打个招呼，Hi~', url_for(:controller => :greeting, :action => :create, :target_user => @user.id, :event_id => @event.id) %>
      </dl>
      <% end %>
      <dl>
        <%= '你已申请加Ta为好友' if @friendship_to && !@friendship_from%>
        <%= link_to '查看该好友的更多信息', url_for(:controller => :profile, :action => :show, :target_user => @user.id) if @friendship_from && @friendship_to %>
        <%=  link_to "申请加为好友", url_for(:controller => :friendship, :action => :add_or_remove, :target_user => @user.id) if !@friendship_to && !@friendship_from%>
        <%=  link_to "同意Ta成为你的好友", url_for(:controller => :friendship, :action => :add_or_remove, :target_user => @user.id) if !@friendship_to && @friendship_from%>
      </dl>
      <% if @friendship_to %>
      <dl>
        <%=  link_to "删除好友", url_for(:controller => :friendship, :action => :add_or_remove, :target_user => @user.id)%>
      </dl>
      <% end %>
    <% end %>
    </dl>
  </td>
</tr></table>
</td></tr>

app/views/shared/_user_profile.mobile.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<li>
  <% if @user.public? %>
    <%= link_to @name, '/public/user/'+@user.id.to_s %>
  <% else %>
    <%=@name%>
  <% end %>
  <%= link_to "查看头像", @photo_url unless (@photo_url.nil? || @photo_url.blank?) %>
  <% unless (@renren_url.nil? || @renren_url.blank?) %>
    <%= link_to "人人主页", @renren_id ? generate_renren_url(@renren_id, true) : @renren_url, :target=>"_blank" %>
    <% if @unconfirmed %>
      <% notice = '人人链接旁边的（？）表示同享日程显示的人人链接并没有得到其本人的确认，但是同享日程觉得这很有可能就是其本人的人人链接' %>
      <%= link_to '（?）', request.request_uri + (request.request_uri.include?('?') ? '&' : '?') + 'notice=' + notice, :title => notice %>
    <% end %>
  <% end %>
  <% if @department && !@department.blank? %>
    <br/><%= @department %>
  <% end %>
  <% if @can_be_selected %>
    <br/><%=  link_to "这是我的人人链接", url_for(:controller => :profile, :action => :select, :renren_url => @renren_url, :department => @department, :photo_url => @photo_url) %>
    <% elsif (current_user && @user.id != current_user.id) %>
      <% if @event %>
      <br/>
        <%= link_to '打个招呼，Hi~', url_for(:controller => :greeting, :action => :create, :target_user => @user.id, :event_id => @event.id) %>
      <% end %>
      <br/>
        <%= '你已申请加Ta为好友' if @friendship_to && !@friendship_from%>
        <%= link_to '查看该好友的更多信息', url_for(:controller => :profile, :action => :show, :target_user => @user.id) if @friendship_from && @friendship_to %>
        <%=  link_to "申请加为好友", url_for(:controller => :friendship, :action => :add_or_remove, :target_user => @user.id) if !@friendship_to && !@friendship_from%>
        <%=  link_to "同意Ta成为你的好友", url_for(:controller => :friendship, :action => :add_or_remove, :target_user => @user.id) if !@friendship_to && @friendship_from%>
      <% if @friendship_to %>
      <br/>
          <%=  link_to "删除好友", url_for(:controller => :friendship, :action => :add_or_remove, :target_user => @user.id)%>
      <% end %>
    <% end %>
</li>