config/routes.rb
Tongshare::Application.routes.draw do

  get "greeting/create"
  get "greeting/index"

  get "friendship/add_or_remove"
  get "friendship/show"

  get "profile/index"
  get "profile/show"
  get "profile/select"

  get "search/index"
  get "search/add_members"
  post "search/add_members"
  get "search/box"
  post "search/box"
  match "search/user/:keyword" => "search#user"
  match "search/location/:keyword" => "search#location"
  match "search/public_user/:keyword" => "search#public_user"
  match "search/public_group/:keyword" => "search#public_group"

  get "public/get_diff"
  match "public/user/:user_id" => "public#show_public_user"
  match "public/group/:group_id" => "public#show_public_group"
  match "public/location/:location" => "public#show_location"

  get "curriculum/upload"
  get "curriculum/save"
  post "curriculum/save"

  get "acceptance/create"
  get "acceptance/destroy"
  get "acceptance/deny"
  get "acceptance/accept"
  get "acceptance/exit"

  post "auth/confirm"

  get "thuauth/auth_with_xls_and_get_name"
  post "thuauth/auth_with_xls_and_get_name"

  devise_for :users, :controllers => {
    :registrations => "registrations_extended", 
    :sessions => "sessions_extended",
    :confirmations => "confirmations_extended"
    }

  get "home/index"

  get "sharings/add_members"
  post "sharings/add_members"

  get "groups/add_members"
  post "groups/add_members"
  get "groups/add_members"
  post "groups/set_members"

  resources :groups
  resources :events
  resources :sharings
  resources :acceptances

  root :to => "home#index"

end

app/controllers/sessions_extended_controller.rb
class SessionsExtendedController < Devise::SessionsController
  include UsersHelper
  def new
    super
  end

  def create
    #find user_id for devise
    user_id_rec = UserIdentifier.find \
      :first,
      :conditions => ["login_type = ? AND login_value = ?",
                      params[:login_type],
                      company_domain + "." + params[:login_value]
      ] #TODO: for other types, no company_domain!!

    #logger.debug "Result: #{user_id_rec.to_yaml}"

    if user_id_rec.nil?
      params[:user][:id] = -1
    else
      params[:user][:id] = user_id_rec.user_id
    end

    #logger.debug params.to_yaml

#    if !user_id_rec.nil? && !user_id_rec.confirmed
#      flash[:notice] = "您的帐号未能通过验证，请尝试重新注册。"
#      redirect_to new_user_registration_path(:employee_no => params[:login_value])
#      return
#    end

    super
  end

end

app/helpers/sessions_extended_helper.rb
module SessionsExtendedHelper
  def login_type_selector(type, checked = false)
    radio = radio_button_tag('login_type', type, checked)
    label = label_tag("login_type_#{type}", I18n.t("activerecord.attributes.user_identifier.#{type}"))
    radio + label
  end
end

app/views/sessions_extended/_login_form.html.erb
<%#= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>

<% small ||= false %>
<%= form_for("user", :url => user_session_path,
                      :html => {:id => "login_form",
                                :class => small ? "login_small" : nil }
            ) do |f| %>
<fieldset style="min-height: 360px;">
<%#*<div class="field">%>
  <%# if small %>
    <%#
    options = <<OPTIONS
        <option value="#{UserIdentifier::TYPE_EMPLOYEE_NO}" selected>学号/工作证号</option>
        <option value="#{UserIdentifier::TYPE_EMAIL}">电子邮件</option>
        <option value="#{UserIdentifier::TYPE_MOBILE}">手机号</option>
OPTIONS
%>
    <%#= select_tag "login_type", options.html_safe, :class => "textvalue"   #seems a bug in rails 3.0, escape < as &lt;. .html_safe goes around it.
    %>

  <%# else %>
  <%#*<label class="title">登录名：</label>%>
    <%#= login_type_selector UserIdentifier::TYPE_EMPLOYEE_NO, true %>
    <%#= login_type_selector UserIdentifier::TYPE_EMAIL %>
   <%#= login_type_selector UserIdentifier::TYPE_MOBILE %>
  <%#end%>
<%#*</div>%>
  <input type="hidden" name="login_type" value="employee_no" />

<div class="field">
  <%# if !small %>
    <label class="title">学号:</label>
  <%#end%>
  <%= text_field_tag :login_value, params[:login_value], :maxlength => UserIdentifier::MAX_VALUE_LENGTH, :class=>"textvalue" %>
</div>

 <div class="field">
  <%= f.label :password, '同享密码:', :class => 'title'%>
  <%= f.password_field :password, :class=>"textvalue"%>
 </div>

 <div class="field">
   <label class="title">&nbsp;</label>
  <%# if devise_mapping.rememberable? -%>
   <%= f.check_box :remember_me, :checked=>true %> <%= f.label :remember_me, '记住我' %>
  <%# end -%>
 </div>
  <div class="register_field">
    <label class="title">&nbsp;</label>
    <%= f.submit :submit, :value => '登录', :class => 'register_button', :border => '0'%>
  </div>
  <hr>
  <div class="register_field">
    <label class="title">&nbsp;</label>
    <a href="/users/sign_up" class="register_button" >立即注册</a>
  </div>
  </fieldset>
<% end %>

app/views/sessions_extended/_login_form.mobile.erb
<%= form_for("user", :url => user_session_path) do |f| %>
     <%#= login_type_selector UserIdentifier::TYPE_EMPLOYEE_NO, true %>
     <%#= login_type_selector UserIdentifier::TYPE_EMAIL %>
     <%#= login_type_selector UserIdentifier::TYPE_MOBILE %>
      学号<br/>
      <input type="hidden" name="login_type" value="employee_no"/>
      <%= text_field_tag :login_value, params[:login_value], :maxlength => UserIdentifier::MAX_VALUE_LENGTH%><br/>
      <%= f.label :password, '密码' %><br/>
      <%= f.password_field :password, :size => nil %><br/>
      <%# if devise_mapping.rememberable? -%>
      <%= f.check_box :remember_me, :checked=>true %> <%= f.label :remember_me, '记住我' %><br/>
      <%# end -%>
      <br/>
      <%= f.submit "登录" %><br/><br/>
      <%= link_to "立即注册", new_user_registration_path %>
 <% end %>

app/views/sessions_extended/new.html.erb
<script src="../javascripts/scriptaculous/src/scriptaculous.js" type="text/javascript"></script>
<script src="../javascripts/image-gallery.js" type="text/javascript"></script>

<div id="content-body">
    <div id="div">
      <div id="div2">
        <h2></h2>
      </div>
      <div id="image-container" style="background-image:url(../images/loading.gif)">
        <div class="fade-box" id="image-1"><a href="javascript:GoNext();"><img src="../images/slides_home/poster.jpg" width="720" height="404" alt="" /></a></div>
        <div class="fade-box" id="image-2" style="display: none;"><a href="javascript:GoNext();"><img src="../images/slides_home/通知2_web.jpg" width="720" height="404" alt="" /></a></div>
        <div class="fade-box" id="image-3" style="display: none;"><a href="javascript:GoNext();"><img src="../images/slides_home/点名2_web.jpg" width="720" height="404" alt="" /></a></div>
        <div class="fade-box" id="image-4" style="display: none;"><a href="javascript:GoNext();"><img src="../images/slides_home/寻觅_web.jpg" width="720" height="404" alt="" /></a></div>
      </div>
    </div>
</div>
<div id="PlayButton"><a href="javascript:StartSlideShow();" style="display: none">PLAY</a></div>
<div id="PauseButton"><a href="javascript:Stop();" style="display: none">STOP</a></div>
<script lang="javascript">StartSlideShow();</script>

<% content_for :aside do %>
<% end %>

app/views/sessions_extended/new.mobile.erb
<h2>登录</h2>

<%= render :partial => "sessions_extended/login_form" %>

<p>同享日程可以：
<ul>
  <% for desc in function_descriptions %>
  <li><%= desc %></li>
  <% end %></ul>
</p>